#!/usr/bin/env python3
"""Generate reviewed straight-line EE kernels. Python only, no toolchain.

--check compares generated text without changing files. Numeric registers
avoid o32/n32 naming differences; saved registers preserve all 128 bits.
"""
from pathlib import Path
import argparse
from collections import Counter

ROOT = Path(__file__).resolve().parents[2]
HEADER = '/* Generated by test/ps2/generate-six-ideas.py; Apache-2.0.\n * Experimental R5900 kernel. No secret-dependent addresses/branches.\n */\n'

def start(name, frame=128):
    lines = [HEADER, '.text', '.set noreorder', '.align 4',
             f'.globl {name}', f'.ent {name}', f'{name}:',
             f'    addiu $sp, $sp, -{frame}']
    lines += [f'    sq ${r}, {(r-16)*16}($sp)' for r in range(16,24)]
    return lines

def finish(lines, name, frame=128, clear=range(8,16)):
    for r in clear: lines.append(f'    pxor ${r}, ${r}, ${r}')
    for r in range(16,24):
        lines += [f'    lq ${r}, {(r-16)*16}($sp)', f'    sq $zero, {(r-16)*16}($sp)']
    lines += [f'    addiu $sp, $sp, {frame}', '    jr $ra', '    nop',
              f'.end {name}', '.set reorder']

def aes_vector():
    # SSA circuit: exactly the scalar tower-field equations, sixteen bytes.
    ops = [('input',)]
    cache = {ops[0]:0}
    def node(op,*args):
        key=(op,*args)
        if key not in cache: cache[key]=len(ops); ops.append(key)
        return cache[key]
    def const(x): return node('const',x)
    def xor(*xs):
        v=xs[0]
        for x in xs[1:]: v=node('pxor',v,x)
        return v
    def shl(x,n): return x if not n else node('psllw',x,n)
    def shr(x,n): return x if not n else node('psrlw',x,n)
    def band(x,m): return node('pand',x,const(m))
    def bits(x,n): return [band(shr(x,i),0x01010101) for i in range(n)]
    def linear(x,terms):
        p=bits(x,len(terms)); v=[]
        for n,indices in enumerate(terms): v.append(shl(xor(*(p[i] for i in indices)),n))
        return xor(*v)
    def sq(x):
        p=bits(x,4)
        return xor(p[0],shl(p[1],2),p[2],shl(p[2],1),shl(p[3],2),shl(p[3],3))
    def lam(x):
        p=bits(x,4)
        return xor(shl(p[0],3),p[1],shl(p[1],1),shl(p[2],1),shl(p[2],2),shl(p[3],2),shl(p[3],3))
    def mul(a,b):
        acc=const(0)
        for i in range(4):
            bit=band(shr(b,i),0x01010101)
            # Broadcast each byte's low bit by shifts, no integer multiply.
            mask=xor(bit,shl(bit,1)); mask=xor(mask,shl(mask,2)); mask=xor(mask,shl(mask,4))
            acc=xor(acc,node('pand',a,mask))
            if i != 3:
                top=band(shr(a,3),0x01010101)
                a=xor(band(shl(a,1),0x0e0e0e0e),top,shl(top,1))
        return acc
    unpack=linear(0,[(0,5,7),(2,),(2,3,4,5,6,7),(3,4),(4,5,6),(1,4,6,7),(2,3,5,7),(5,7)])
    a=band(unpack,0x0f0f0f0f); b=band(shr(unpack,4),0x0f0f0f0f)
    n=xor(sq(a),mul(a,b),lam(sq(b)))
    n2=sq(n); n3=mul(n2,n); n6=sq(n3); n12=sq(n6); ni=mul(n12,n2)
    ai=mul(xor(a,b),ni); bi=mul(b,ni)
    output=xor(linear(xor(ai,shl(bi,4)),[(0,2,6),(0,1,2,3,4,5),(0,3,5,6),(0,2,5),(0,1,3,4,5),(1,2,3,5,6,7),(4,6,7),(1,2)]),const(0x63636363))
    # DFS order frees shared subexpressions at their last use. Spill only
    # if needed; deterministic allocation is checked by instruction replay.
    order=[]; visited=set()
    def visit(i):
        if i in visited: return
        visited.add(i)
        op=ops[i]
        if op[0] in ('pxor','pand'):
            visit(op[1]); visit(op[2])
        elif op[0] in ('psllw','psrlw'): visit(op[1])
        order.append(i)
    visit(output)
    uses=Counter()
    for i in order:
        op=ops[i]
        if op[0] in ('pxor','pand'): uses.update(op[1:])
        elif op[0] in ('psllw','psrlw'): uses[op[1]]+=1
    uses[output]+=1
    name='ossl_ee_aes_subbytes16_mmi'
    lines=start(name,512)
    lines += ['    lui $25, %hi(.Laes_sbox_constants)', '    addiu $25, $25, %lo(.Laes_sbox_constants)']
    constants=sorted({ops[i][1] for i in order if ops[i][0]=='const'})
    free=list(range(2,4))+list(range(5,25)); locations={}; spills={}; nextslot=128
    def alloc(protected):
        nonlocal nextslot
        if free: return free.pop(0)
        victim=next(i for i in locations if i not in protected)
        r=locations.pop(victim)
        if victim not in spills: spills[victim]=nextslot; nextslot+=16
        assert nextslot<=512
        lines.append(f'    sq ${r}, {spills[victim]}($sp)')
        return r
    for i in order:
        op=ops[i]; inputs=op[1:] if op[0] in ('pxor','pand') else op[1:2] if op[0] in ('psllw','psrlw') else ()
        # Reload sources with all sources protected against eviction.
        for v in inputs:
            if v not in locations:
                r=alloc(set(inputs)); lines.append(f'    lq ${r}, {spills[v]}($sp)'); locations[v]=r
        args=[locations[v] for v in inputs]
        for v in inputs:
            uses[v]-=1
        reuse=next((v for v in inputs if uses[v]==0),None)
        if reuse is None: r=alloc(set(inputs))
        else: r=locations.pop(reuse)
        if op[0]=='input': lines.append(f'    lq ${r}, 0($4)')
        elif op[0]=='const': lines.append(f'    lq ${r}, {16*constants.index(op[1])}($25)')
        elif op[0] in ('pxor','pand'): lines.append(f'    {op[0]} ${r}, ${args[0]}, ${args[1]}')
        else: lines.append(f'    {op[0]} ${r}, ${args[0]}, {op[2]}')
        locations[i]=r
        for v in set(inputs):
            if uses[v]==0 and v in locations: free.append(locations.pop(v))
    lines.append(f'    sq ${locations[output]}, 0($4)')
    for off in range(128,nextslot,16): lines.append(f'    sq $zero, {off}($sp)')
    finish(lines,name,512,[2,3,*range(5,16),24,25])
    lines+=['.section .rodata','.align 4','.Laes_sbox_constants:']
    lines += ['    .word '+', '.join([hex(x)]*4) for x in constants]
    return '\n'.join(lines)+'\n'

def p256_mul():
    name='ossl_ee_p256_mul8_mmi'; s=start(name)
    s += [f'    pxor ${r}, ${r}, ${r}' for r in range(16,26)]
    s += ['    addiu $7, $zero, 8','.Lp256_mul_row:', '    lw $8, 0($6)', '    pcpyld $9, $8, $8','    daddu $15, $zero, $zero']
    for j in range(0,8,2):
        s += [f'    lw $10, {4*j}($5)',f'    lw $11, {4*j+4}($5)',
              '    pcpyld $12, $11, $10','    pmultuw $13, $12, $9','    pcpyud $14, $13, $13']
        for k,prod in ((j,13),(j+1,14)):
            s += [f'    daddu $3, ${prod}, ${16+k}','    daddu $3, $3, $15',
                  '    dsrl32 $15, $3, 0',f'    dsll32 ${16+k}, $3, 0',f'    dsrl32 ${16+k}, ${16+k}, 0']
    s += ['    daddu $3, $24, $15','    dsrl32 $8, $3, 0','    daddu $25, $25, $8','    dsll32 $24, $3, 0','    dsrl32 $24, $24, 0',
          '    daddu $15, $16, $zero','    dsll32 $8, $16, 0','    dsubu $8, $8, $16']
    for j in range(1,8):
        prod='$8' if j in (1,2,7) else '$16' if j==6 else '$zero'
        # q originally t0 must survive overwrite of t0: keep it in $2.
        if j==1: s.append('    daddu $2, $16, $zero')
        if j==6: prod='$2'
        s += [f'    daddu $3, ${16+j}, {prod}','    daddu $3, $3, $15',
              '    dsrl32 $15, $3, 0',f'    dsll32 ${15+j}, $3, 0',f'    dsrl32 ${15+j}, ${15+j}, 0']
    s += ['    daddu $3, $24, $15','    dsrl32 $8, $3, 0','    daddu $24, $25, $8',
          '    dsll32 $23, $3, 0','    dsrl32 $23, $23, 0','    daddu $25, $zero, $zero',
          '    addiu $7, $7, -1','    bnez $7, .Lp256_mul_row','    addiu $6, $6, 4',
          '    daddu $15, $zero, $zero','    lui $8, 0xffff','    ori $8, $8, 0xffff','    dsll32 $8, $8, 0','    dsrl32 $8, $8, 0']
    for j in range(8):
        s.append('    daddu $9, '+('$8' if j in (0,1,2,7) else '$zero')+', $15')
        if j==6: s.append('    addiu $9, $15, 1')
        s += [f'    sltu $15, ${16+j}, $9',f'    dsubu $3, ${16+j}, $9',f'    sw $3, {4*j}($4)']
    s += ['    sltiu $9, $24, 1','    and $9, $9, $15','    dsubu $9, $zero, $9','    nor $10, $9, $zero']
    for j in range(8):
        s += [f'    lwu $3, {4*j}($4)','    and $3, $3, $10',f'    and $11, ${16+j}, $9','    or $3, $3, $11',f'    sw $3, {4*j}($4)']
    s += ['    pmultuw $12, $zero, $zero']
    finish(s,name,clear=[2,3,7,*range(8,16),24,25])
    return '\n'.join(s)+'\n'

def x25519_fused():
    name='ossl_ee_x25519_mul_reduce4'; s=start(name)
    for group,extract in enumerate(('pextlw','pextuw')):
        for k in range(10):
            for i in range(10):
                j=(k-i)%10; scale=(2 if i&j&1 else 1)*(19 if i+j>=10 else 1)
                off={1:0,2:160,19:320,38:480}[scale]+16*j
                s += [f'    lq $8, {16*i}($5)',f'    lq $9, {off}($6)',
                      f'    {extract} $10, $zero, $8',f'    {extract} $11, $zero, $9',
                      f'    {"pmultuw" if i==0 else "pmadduw"} $12, $10, $11']
            s.append(f'    por ${16+k}, $12, $zero')
        # Two independent unsigned 64-bit lanes; no packed 64-bit ADD exists.
        for rep in range(3):
            for k in range(10):
                width=25 if k&1 else 26
                s += [f'    ori $13, $zero, 1',f'    dsll $13, $13, {width}','    addiu $13, $13, -1',
                      '    pcpyld $13, $13, $13',f'    dsrl $8, ${16+k}, {width}',
                      f'    pcpyud $9, ${16+k}, ${16+k}',f'    dsrl $9, $9, {width}',
                      f'    pand ${16+k}, ${16+k}, $13']
                dest=16+k+1 if k<9 else 16
                if k==9:
                    for r in (8,9):
                        s += [f'    dsll $10, ${r}, 4',f'    dsll $11, ${r}, 1',f'    daddu $10, $10, $11',f'    daddu ${r}, $10, ${r}']
                s += [f'    daddu $10, ${dest}, $8',f'    pcpyud $11, ${dest}, ${dest}',
                      '    daddu $11, $11, $9',f'    pcpyld ${dest}, $11, $10']
        for k in range(10):
            s += [f'    sw ${16+k}, {16*k+8*group}($4)',f'    pcpyud $8, ${16+k}, ${16+k}',f'    sw $8, {16*k+8*group+4}($4)']
    s += ['    pmultuw $12, $zero, $zero']
    finish(s,name,clear=[*range(8,16),24,25])
    return '\n'.join(s)+'\n'

def p256_square():
    # 96-bit Comba accumulator handles doubled 64-bit cross-products.
    name='ossl_ee_p256_square_words_mmi'; s=[HEADER,'.text','.set noreorder','.align 4',f'.globl {name}',f'.ent {name}',f'{name}:',
        '    daddu $8, $zero, $zero','    daddu $9, $zero, $zero']
    for k in range(15):
        terms=[(i,k-i) for i in range(8) if i<=k-i<8]
        for idx in range(0,len(terms),2):
            batch=terms[idx:idx+2]
            for lane,(i,j) in enumerate(batch):
                s += [f'    lw ${10+lane}, {4*i}($5)',f'    lw ${12+lane}, {4*j}($5)']
            if len(batch)==1: s += ['    daddu $11, $zero, $zero','    daddu $13, $zero, $zero']
            s += ['    pcpyld $10, $11, $10','    pcpyld $12, $13, $12','    pmultuw $14, $10, $12','    pcpyud $15, $14, $14']
            for lane,(i,j) in enumerate(batch):
                prod=14+lane
                for _ in range(1 if i==j else 2):
                    s += [f'    daddu $10, $8, ${prod}','    sltu $11, $10, $8','    daddu $9, $9, $11','    daddu $8, $10, $zero']
        s += [f'    sw $8, {4*k}($4)','    dsrl32 $8, $8, 0','    dsll32 $10, $9, 0','    or $8, $8, $10','    dsrl32 $9, $9, 0']
    s += ['    sw $8, 60($4)','    sw $zero, 64($4)','    sw $zero, 68($4)','    pmultuw $12, $zero, $zero']
    for r in range(8,16): s.append(f'    pxor ${r}, ${r}, ${r}')
    s += ['    jr $ra','    nop',f'.end {name}','.set reorder']
    return '\n'.join(s)+'\n'

def outputs():
    return {'crypto/aes/aes-ee-subbytes-mmi.S':aes_vector(),
            'crypto/ec/p256-ee-mul8-mmi.S':p256_mul(),
            'crypto/ec/x25519-ee-reduce-mmi.S':x25519_fused(),
            'crypto/ec/p256-ee-square-mmi.S':p256_square()}

if __name__=='__main__':
    ap=argparse.ArgumentParser(); ap.add_argument('--check',action='store_true'); args=ap.parse_args()
    for path,text in outputs().items():
        if args.check: assert (ROOT/path).read_text(encoding='utf-8')==text,path
        else: (ROOT/path).write_bytes(text.encode('utf-8'))
    print('PASS: four deterministic EE kernel sources'+(' match generators' if args.check else ' generated'))
